num_nodes: 1
precision: 32-true
logger:
  - class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: resnext-full-dataset
      save_dir: logs
      project: Test
callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
        verbose: True
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
  # - class_path: pytorch_lightning.callbacks.EarlyStopping
  #   init_args:
  #       patience: 10
  #       monitor: val_loss
fast_dev_run: false
max_epochs: 1000
max_steps: -1
limit_train_batches: null
limit_val_batches: null
limit_test_batches: null
limit_predict_batches: null
overfit_batches: 0.0
val_check_interval: null
check_val_every_n_epoch: 1
log_every_n_steps: null
accumulate_grad_batches: 10
gradient_clip_val: 1.0
plugins:
  - class_path: lightning_fabric.plugins.environments.SLURMEnvironment
    init_args:
      auto_requeue: True
      requeue_signal: SIGTERM
      # requeue_signal: SIGUSR1